### ISSUE TITLE
DE Certificate of Good Standing Backlog

### ISSUE THREAD

**Issue by MikeShi42** [leonar15/startup-checklist#17]
Just wanted to mention when I filed online to get my company's cert of good standing from DE for the california foreign entity registration - I was told the "normal" speed filings are backlogged for months, and even the "24 hour" filing speed option will take a week.

I didn't find out about this until contacting DE support. I ended up upgrading to "Same Day" filing speed for my request - which indeed did get processed same day and arrived in the post a few days later.

Perhaps this should be noted somewhere in the README for others to not make the same mistake I did and just opt for 24 hour or same day filing speed (it was only I think $50 extra) to avoid the huge backlog.

**Comment by leonar15** [comment]
Thanks for the heads up about this delay!

I've added a note referencing this delay (https://github.com/leonar15/startup-checklist/commit/2d5b6ac80fbd3b6695b7e9bd0a53caf9e5493d3b).
